/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as MailComposeRouteImport } from "./routes/mail/compose";
import { Route as MailInboxRouteImport } from "./routes/mail/inbox";
import { Route as MailRouteRouteImport } from "./routes/mail/route";
import { Route as MailTrashRouteImport } from "./routes/mail/trash";
import { Route as SettingsAppearanceRouteImport } from "./routes/settings/appearance";
import { Route as SettingsImportRouteImport } from "./routes/settings/import";
import { Route as SettingsProfileRouteImport } from "./routes/settings/profile";
import { Route as SettingsRouteRouteImport } from "./routes/settings/route";
import { Route as SigninRouteImport } from "./routes/signin";

const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const MailRouteRoute = MailRouteRouteImport.update({
  id: "/mail",
  path: "/mail",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsImportRoute = SettingsImportRouteImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: "/appearance",
  path: "/appearance",
  getParentRoute: () => SettingsRouteRoute,
} as any);
const MailTrashRoute = MailTrashRouteImport.update({
  id: "/trash",
  path: "/trash",
  getParentRoute: () => MailRouteRoute,
} as any);
const MailInboxRoute = MailInboxRouteImport.update({
  id: "/inbox",
  path: "/inbox",
  getParentRoute: () => MailRouteRoute,
} as any);
const MailComposeRoute = MailComposeRouteImport.update({
  id: "/compose",
  path: "/compose",
  getParentRoute: () => MailRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/mail": typeof MailRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/mail/compose": typeof MailComposeRoute;
  "/mail/inbox": typeof MailInboxRoute;
  "/mail/trash": typeof MailTrashRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/import": typeof SettingsImportRoute;
  "/settings/profile": typeof SettingsProfileRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/mail": typeof MailRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/mail/compose": typeof MailComposeRoute;
  "/mail/inbox": typeof MailInboxRoute;
  "/mail/trash": typeof MailTrashRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/import": typeof SettingsImportRoute;
  "/settings/profile": typeof SettingsProfileRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/mail": typeof MailRouteRouteWithChildren;
  "/settings": typeof SettingsRouteRouteWithChildren;
  "/signin": typeof SigninRoute;
  "/mail/compose": typeof MailComposeRoute;
  "/mail/inbox": typeof MailInboxRoute;
  "/mail/trash": typeof MailTrashRoute;
  "/settings/appearance": typeof SettingsAppearanceRoute;
  "/settings/import": typeof SettingsImportRoute;
  "/settings/profile": typeof SettingsProfileRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/mail"
    | "/settings"
    | "/signin"
    | "/mail/compose"
    | "/mail/inbox"
    | "/mail/trash"
    | "/settings/appearance"
    | "/settings/import"
    | "/settings/profile";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/mail"
    | "/settings"
    | "/signin"
    | "/mail/compose"
    | "/mail/inbox"
    | "/mail/trash"
    | "/settings/appearance"
    | "/settings/import"
    | "/settings/profile";
  id:
    | "__root__"
    | "/"
    | "/mail"
    | "/settings"
    | "/signin"
    | "/mail/compose"
    | "/mail/inbox"
    | "/mail/trash"
    | "/settings/appearance"
    | "/settings/import"
    | "/settings/profile";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MailRouteRoute: typeof MailRouteRouteWithChildren;
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren;
  SigninRoute: typeof SigninRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signin": {
      id: "/signin";
      path: "/signin";
      fullPath: "/signin";
      preLoaderRoute: typeof SigninRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/mail": {
      id: "/mail";
      path: "/mail";
      fullPath: "/mail";
      preLoaderRoute: typeof MailRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings/profile": {
      id: "/settings/profile";
      path: "/profile";
      fullPath: "/settings/profile";
      preLoaderRoute: typeof SettingsProfileRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/import": {
      id: "/settings/import";
      path: "/import";
      fullPath: "/settings/import";
      preLoaderRoute: typeof SettingsImportRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/settings/appearance": {
      id: "/settings/appearance";
      path: "/appearance";
      fullPath: "/settings/appearance";
      preLoaderRoute: typeof SettingsAppearanceRouteImport;
      parentRoute: typeof SettingsRouteRoute;
    };
    "/mail/trash": {
      id: "/mail/trash";
      path: "/trash";
      fullPath: "/mail/trash";
      preLoaderRoute: typeof MailTrashRouteImport;
      parentRoute: typeof MailRouteRoute;
    };
    "/mail/inbox": {
      id: "/mail/inbox";
      path: "/inbox";
      fullPath: "/mail/inbox";
      preLoaderRoute: typeof MailInboxRouteImport;
      parentRoute: typeof MailRouteRoute;
    };
    "/mail/compose": {
      id: "/mail/compose";
      path: "/compose";
      fullPath: "/mail/compose";
      preLoaderRoute: typeof MailComposeRouteImport;
      parentRoute: typeof MailRouteRoute;
    };
  }
}

interface MailRouteRouteChildren {
  MailComposeRoute: typeof MailComposeRoute;
  MailInboxRoute: typeof MailInboxRoute;
  MailTrashRoute: typeof MailTrashRoute;
}

const MailRouteRouteChildren: MailRouteRouteChildren = {
  MailComposeRoute: MailComposeRoute,
  MailInboxRoute: MailInboxRoute,
  MailTrashRoute: MailTrashRoute,
};

const MailRouteRouteWithChildren = MailRouteRoute._addFileChildren(
  MailRouteRouteChildren,
);

interface SettingsRouteRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute;
  SettingsImportRoute: typeof SettingsImportRoute;
  SettingsProfileRoute: typeof SettingsProfileRoute;
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsImportRoute: SettingsImportRoute,
  SettingsProfileRoute: SettingsProfileRoute,
};

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MailRouteRoute: MailRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SigninRoute: SigninRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
